# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f55e50284a50554aae432999062a1111"
name = "whatsapp-flow"
handle = "whatsapp-flow-2"
application_url = "https://ruling-printable-exit-somehow.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://ruling-printable-exit-somehow.trycloudflare.com/auth/callback", "https://ruling-printable-exit-somehow.trycloudflare.com/auth/shopify/callback", "https://ruling-printable-exit-somehow.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
